load(
    "//private/providers:runfilesgroupinfo.bzl",
    _RunfilesGroupInfo = "RunfilesGroupInfo",
)

load(
    "//private:well_known_groups.bzl",
    _SAME_PARTY_RUNFILES = "SAME_PARTY_RUNFILES",
    _OTHER_PARTY_RUNFILES = "OTHER_PARTY_RUNFILES",
    _FOUNDATIONAL_RUNFILES = "FOUNDATIONAL_RUNFILES",
    _DEBUG_RUNFILES = "DEBUG_RUNFILES",
    _DOCUMENTATION_RUNFILES = "DOCUMENTATION_RUNFILES",
)

RunfilesGroupInfo = _RunfilesGroupInfo

SAME_PARTY_RUNFILES = _SAME_PARTY_RUNFILES
OTHER_PARTY_RUNFILES = _OTHER_PARTY_RUNFILES
FOUNDATIONAL_RUNFILES = _FOUNDATIONAL_RUNFILES
DEBUG_RUNFILES = _DEBUG_RUNFILES
DOCUMENTATION_RUNFILES = _DOCUMENTATION_RUNFILES
